
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { Connection } from '../types/Connection'

export default function ConnectionsList() {
  // get connections from api
  const connections: Connection[] = [];
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Your connections
        </h1>
        <p className={styles.description}>
          Here you can add new connections and browse existing ones
        </p>
        <div className={styles.grid}>
          <a href="https://github.com/kirilligum/fevm-deskilne" className={styles.card}>
            <h2>What is Deskilne? &rarr;</h2>
            <p>Decentralized professional networking tool</p>
          </a>
          <ul>
            {
              connections.map((v: Connection, i) => {
                return <li key={`connection-${i}`}>
                  address: {v.recipientAddress}
                  stake: {v.stake}
                </li>
              })
            }
          </ul>
        </div>
      </main>

 
    </div>
  )
}
