
import Head from 'next/head'
import Layout from '../components/layout'
import styles from '../styles/Home.module.css'
import { Connection } from '../types/Connection'

export default function ConnectionsList() {
  const connections: Connection[] = [];
  return (
    <div className={styles.container}>
      <Head>
        <title>Deskilne Connections</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className={styles.main}>
          <h1 className={styles.title}>
            Your connections
          </h1>
          <p className={styles.description}>
            Here you can add new connections and browse existing ones
          </p>
          <div className={styles.grid}>
            <ul>
              {
                connections.map((v: Connection, i) => {
                  return <li key={`connection-${i}`}>
                    address: {v.recipientAddress}
                    stake: {v.stake}
                  </li>
                })
              }
            </ul>
          </div>
        </main>
      </Layout>
    </div>
  )
}
