

import Head from 'next/head'
import Layout from '../components/layout';
import styles from '../styles/Home.module.css'
import { Connection } from '../types/Connection'

export default function Messages() {
  // get connections from api
  const connections: Connection[] = [];
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className={styles.main}>
          <h1 className={styles.title}>
            Your message history
          </h1>
          <div className={styles.grid}>
            <ul>
              {
                connections.map((v: Connection, i) => {
                  return <li key={`connection-${i}`}>
                    address: {v.recipientAddress}
                    stake: {v.stake}
                    <button onClick={() => console.log('will send message')}>
                      Send them a message
                    </button>
                  </li>
                })
              }
            </ul>
          </div>
        </main>
      </Layout>
    </div>
  )
}
